#server:
#  port: 8060
#  host: "localhost"
#  sockets:
#    - name: "private"
#      port: 8061
#    - name: "admin"
#      port: 8062
#      # bind address is optional, if not defined, server host will be used)
#      bind-address: "localhost"
#  features:
#    observe:
#      # Metrics and health run on admin port
#      sockets: "admin"
security:
  providers:
    - abac:
    - http-basic-auth:
        realm: "helidon"
        users:
          - login: "dodex"
            password: "dodex"
            roles: ["admin"]
          - login: "user"
            password: "user"
            roles: ["user"]
          - login: "not"
            password: "allowed"
  webserver:
    paths:
      - path: "/test[/{*}]"
        authenticate: false
      - path: "/addGroup[/{*}]"
        authenticate: true
#idle-connection-timeout: PT30M
#websocket:
#  idle-connection-timeout: PT30M
javax:
  sql:
    DataSource:
      dsdb2dev:
        dataSourceClassName: com.ibm.db2.jcc.DB2SimpleDataSource
        dataSource:
          user: db2inst1
          password: dodex
          databaseName: testdb
          serverName: localhost
          portNumber: 50000
          currentSchema: DB2INST1
          driverType: 4
          progressiveStreaming: 2 # set to 1 to use
      dsdb2prod:
        dataSourceClassName: com.ibm.db2.jcc.DB2SimpleDataSource
        dataSource:
          user: db2inst1
          password: dodex
          databaseName: dodex
          serverName: localhost
          portNumber: 50000
          currentSchema: DB2INST1
          driverType: 4
          progressiveStreaming: 2
