server:
  idle-connection-timeout: PT30M
  port: 8060
#  host: "0.0.0.0"
  features:
    observe:
      observers:
        health:
          details: true
#  sockets:
#    - name: "grpc"
#      port: 8061
#      bind-address: "localhost"
#    - name: "private"
#      port: 8061
#    - name: "admin"
#      port: 8062
#      # bind address is optional, if not defined, server host will be used)
#      bind-address: "localhost"
#  features:
#    observe:
#      # Metrics and health run on admin port
#      sockets: "admin"
security:
  providers:
    - abac:
    - http-basic-auth:
        realm: "helidon"
        users:
          - login: "dodex"
            password: "dodex"
            roles: ["admin"]
          - login: "user"
            password: "user"
            roles: ["user"]
          - login: "not"
            password: "allowed"
  webserver:
    paths:
      - path: "/test[/{*}]"
        authenticate: false
      - path: "/addGroup[/{*}]"
        authenticate: true
health:
  routing: "admin"
port: 8061

handicap:
  enable.admin: false
  admin.pin: "hand!cap"